// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dispatch/v1/dispatch.proto

package dispatchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunnerMode int32

const (
	RunnerMode_RUNNER_MODE_UNSPECIFIED RunnerMode = 0
	RunnerMode_RUNNER_MODE_HOST        RunnerMode = 1
	RunnerMode_RUNNER_MODE_DOCKER      RunnerMode = 2
	RunnerMode_RUNNER_MODE_K8S         RunnerMode = 3
)

// Enum value maps for RunnerMode.
var (
	RunnerMode_name = map[int32]string{
		0: "RUNNER_MODE_UNSPECIFIED",
		1: "RUNNER_MODE_HOST",
		2: "RUNNER_MODE_DOCKER",
		3: "RUNNER_MODE_K8S",
	}
	RunnerMode_value = map[string]int32{
		"RUNNER_MODE_UNSPECIFIED": 0,
		"RUNNER_MODE_HOST":        1,
		"RUNNER_MODE_DOCKER":      2,
		"RUNNER_MODE_K8S":         3,
	}
)

func (x RunnerMode) Enum() *RunnerMode {
	p := new(RunnerMode)
	*p = x
	return p
}

func (x RunnerMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunnerMode) Descriptor() protoreflect.EnumDescriptor {
	return file_dispatch_v1_dispatch_proto_enumTypes[0].Descriptor()
}

func (RunnerMode) Type() protoreflect.EnumType {
	return &file_dispatch_v1_dispatch_proto_enumTypes[0]
}

func (x RunnerMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunnerMode.Descriptor instead.
func (RunnerMode) EnumDescriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{0}
}

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE_PENDING     Phase = 1
	Phase_PHASE_RUNNING     Phase = 2
	Phase_PHASE_SUCCESS     Phase = 3
	Phase_PHASE_FAILURE     Phase = 4
	Phase_PHASE_SKIPPED     Phase = 5
	Phase_PHASE_CANCELLED   Phase = 6
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_PENDING",
		2: "PHASE_RUNNING",
		3: "PHASE_SUCCESS",
		4: "PHASE_FAILURE",
		5: "PHASE_SKIPPED",
		6: "PHASE_CANCELLED",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_PENDING":     1,
		"PHASE_RUNNING":     2,
		"PHASE_SUCCESS":     3,
		"PHASE_FAILURE":     4,
		"PHASE_SKIPPED":     5,
		"PHASE_CANCELLED":   6,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_dispatch_v1_dispatch_proto_enumTypes[1].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_dispatch_v1_dispatch_proto_enumTypes[1]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{1}
}

type RegisterRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Mode          RunnerMode             `protobuf:"varint,3,opt,name=mode,proto3,enum=dispatch.v1.RunnerMode" json:"mode,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"` // max concurrent jobs
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRunnerRequest) Reset() {
	*x = RegisterRunnerRequest{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRunnerRequest) ProtoMessage() {}

func (x *RegisterRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRunnerRequest.ProtoReflect.Descriptor instead.
func (*RegisterRunnerRequest) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRunnerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRunnerRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRunnerRequest) GetMode() RunnerMode {
	if x != nil {
		return x.Mode
	}
	return RunnerMode_RUNNER_MODE_UNSPECIFIED
}

func (x *RegisterRunnerRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RegisterRunnerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RegisterRunnerResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RunnerId                 string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	AuthToken                string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterRunnerResponse) Reset() {
	*x = RegisterRunnerResponse{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRunnerResponse) ProtoMessage() {}

func (x *RegisterRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRunnerResponse.ProtoReflect.Descriptor instead.
func (*RegisterRunnerResponse) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRunnerResponse) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RegisterRunnerResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RegisterRunnerResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type AcquireJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	FreeSlots     int32                  `protobuf:"varint,2,opt,name=free_slots,json=freeSlots,proto3" json:"free_slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireJobRequest) Reset() {
	*x = AcquireJobRequest{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireJobRequest) ProtoMessage() {}

func (x *AcquireJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireJobRequest.ProtoReflect.Descriptor instead.
func (*AcquireJobRequest) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{2}
}

func (x *AcquireJobRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *AcquireJobRequest) GetFreeSlots() int32 {
	if x != nil {
		return x.FreeSlots
	}
	return 0
}

// NeedOutputs carries a completed upstream job's distilled result so the runner
// can hydrate wf.Jobs[need].Outputs / .Result before executing (cross-machine
// needs bridge).
type NeedOutputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // success|failure|cancelled|skipped
	Outputs       map[string]string      `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedOutputs) Reset() {
	*x = NeedOutputs{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedOutputs) ProtoMessage() {}

func (x *NeedOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedOutputs.ProtoReflect.Descriptor instead.
func (*NeedOutputs) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{3}
}

func (x *NeedOutputs) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *NeedOutputs) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// JobLease is a single job to run. It carries the verbatim workflow YAML plus
// which job_id + matrix cell — the runner re-parses the YAML to rebuild an
// identical model.Workflow. It never contains other jobs' steps or the DAG.
type JobLease struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	LeaseId           string                  `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	JobRunId          string                  `protobuf:"bytes,2,opt,name=job_run_id,json=jobRunId,proto3" json:"job_run_id,omitempty"` // orchestrator "jobs" row id
	WorkflowYaml      string                  `protobuf:"bytes,3,opt,name=workflow_yaml,json=workflowYaml,proto3" json:"workflow_yaml,omitempty"`
	JobId             string                  `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                              // key in workflow.jobs
	MatrixCellJson    string                  `protobuf:"bytes,5,opt,name=matrix_cell_json,json=matrixCellJson,proto3" json:"matrix_cell_json,omitempty"` // JSON object for this matrix cell, or ""
	EventName         string                  `protobuf:"bytes,6,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`                  // push|pull_request|manual...
	EventJson         string                  `protobuf:"bytes,7,opt,name=event_json,json=eventJson,proto3" json:"event_json,omitempty"`                  // github.event.* payload
	RepoUrl           string                  `protobuf:"bytes,8,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Ref               string                  `protobuf:"bytes,9,opt,name=ref,proto3" json:"ref,omitempty"`
	Sha               string                  `protobuf:"bytes,10,opt,name=sha,proto3" json:"sha,omitempty"`
	Actor             string                  `protobuf:"bytes,11,opt,name=actor,proto3" json:"actor,omitempty"`
	Env               map[string]string       `protobuf:"bytes,12,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Vars              map[string]string       `protobuf:"bytes,13,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Secrets           map[string]string       `protobuf:"bytes,14,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NeedsOutputs      map[string]*NeedOutputs `protobuf:"bytes,15,rep,name=needs_outputs,json=needsOutputs,proto3" json:"needs_outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // keyed by need job_id
	LeaseDeadlineUnix int64                   `protobuf:"varint,16,opt,name=lease_deadline_unix,json=leaseDeadlineUnix,proto3" json:"lease_deadline_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JobLease) Reset() {
	*x = JobLease{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLease) ProtoMessage() {}

func (x *JobLease) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLease.ProtoReflect.Descriptor instead.
func (*JobLease) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{4}
}

func (x *JobLease) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *JobLease) GetJobRunId() string {
	if x != nil {
		return x.JobRunId
	}
	return ""
}

func (x *JobLease) GetWorkflowYaml() string {
	if x != nil {
		return x.WorkflowYaml
	}
	return ""
}

func (x *JobLease) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobLease) GetMatrixCellJson() string {
	if x != nil {
		return x.MatrixCellJson
	}
	return ""
}

func (x *JobLease) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *JobLease) GetEventJson() string {
	if x != nil {
		return x.EventJson
	}
	return ""
}

func (x *JobLease) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *JobLease) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *JobLease) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *JobLease) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *JobLease) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *JobLease) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *JobLease) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *JobLease) GetNeedsOutputs() map[string]*NeedOutputs {
	if x != nil {
		return x.NeedsOutputs
	}
	return nil
}

func (x *JobLease) GetLeaseDeadlineUnix() int64 {
	if x != nil {
		return x.LeaseDeadlineUnix
	}
	return 0
}

type HeartbeatPing struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunnerId       string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	ActiveLeaseIds []string               `protobuf:"bytes,2,rep,name=active_lease_ids,json=activeLeaseIds,proto3" json:"active_lease_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatPing) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *HeartbeatPing) GetActiveLeaseIds() []string {
	if x != nil {
		return x.ActiveLeaseIds
	}
	return nil
}

type HeartbeatAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NextIntervalSeconds int32                  `protobuf:"varint,1,opt,name=next_interval_seconds,json=nextIntervalSeconds,proto3" json:"next_interval_seconds,omitempty"`
	CancelLeaseIds      []string               `protobuf:"bytes,2,rep,name=cancel_lease_ids,json=cancelLeaseIds,proto3" json:"cancel_lease_ids,omitempty"` // orchestrator asks runner to cancel these
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatAck) GetNextIntervalSeconds() int32 {
	if x != nil {
		return x.NextIntervalSeconds
	}
	return 0
}

func (x *HeartbeatAck) GetCancelLeaseIds() []string {
	if x != nil {
		return x.CancelLeaseIds
	}
	return nil
}

type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"` // "" for job-level
	StepIndex     int32                  `protobuf:"varint,3,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	StepName      string                 `protobuf:"bytes,4,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Phase         Phase                  `protobuf:"varint,5,opt,name=phase,proto3,enum=dispatch.v1.Phase" json:"phase,omitempty"`
	TsUnix        int64                  `protobuf:"varint,6,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{7}
}

func (x *StatusUpdate) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *StatusUpdate) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StatusUpdate) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *StatusUpdate) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StatusUpdate) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *StatusUpdate) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

type StatusAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusAck) Reset() {
	*x = StatusAck{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAck) ProtoMessage() {}

func (x *StatusAck) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAck.ProtoReflect.Descriptor instead.
func (*StatusAck) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{8}
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"` // monotonic per lease, for ordering + idempotent append
	TsUnix        int64                  `protobuf:"varint,4,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{9}
}

func (x *LogChunk) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LogChunk) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *LogChunk) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogChunk) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LogAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAck) Reset() {
	*x = LogAck{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAck) ProtoMessage() {}

func (x *LogAck) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAck.ProtoReflect.Descriptor instead.
func (*LogAck) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{10}
}

type CompleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Result        Phase                  `protobuf:"varint,2,opt,name=result,proto3,enum=dispatch.v1.Phase" json:"result,omitempty"` // SUCCESS|FAILURE|CANCELLED
	Outputs       map[string]string      `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ErrorSummary  string                 `protobuf:"bytes,4,opt,name=error_summary,json=errorSummary,proto3" json:"error_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobRequest) Reset() {
	*x = CompleteJobRequest{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobRequest) ProtoMessage() {}

func (x *CompleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobRequest.ProtoReflect.Descriptor instead.
func (*CompleteJobRequest) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteJobRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *CompleteJobRequest) GetResult() Phase {
	if x != nil {
		return x.Result
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *CompleteJobRequest) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *CompleteJobRequest) GetErrorSummary() string {
	if x != nil {
		return x.ErrorSummary
	}
	return ""
}

type CompleteJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobResponse) Reset() {
	*x = CompleteJobResponse{}
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobResponse) ProtoMessage() {}

func (x *CompleteJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_v1_dispatch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobResponse.ProtoReflect.Descriptor instead.
func (*CompleteJobResponse) Descriptor() ([]byte, []int) {
	return file_dispatch_v1_dispatch_proto_rawDescGZIP(), []int{12}
}

var File_dispatch_v1_dispatch_proto protoreflect.FileDescriptor

const file_dispatch_v1_dispatch_proto_rawDesc = "" +
	"\n" +
	"\x1adispatch/v1/dispatch.proto\x12\vdispatch.v1\"\xa6\x01\n" +
	"\x15RegisterRunnerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\x12+\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x17.dispatch.v1.RunnerModeR\x04mode\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\x92\x01\n" +
	"\x16RegisterRunnerResponse\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x05R\x18heartbeatIntervalSeconds\"O\n" +
	"\x11AcquireJobRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x1d\n" +
	"\n" +
	"free_slots\x18\x02 \x01(\x05R\tfreeSlots\"\xa2\x01\n" +
	"\vNeedOutputs\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12?\n" +
	"\aoutputs\x18\x02 \x03(\v2%.dispatch.v1.NeedOutputs.OutputsEntryR\aoutputs\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x06\n" +
	"\bJobLease\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1c\n" +
	"\n" +
	"job_run_id\x18\x02 \x01(\tR\bjobRunId\x12#\n" +
	"\rworkflow_yaml\x18\x03 \x01(\tR\fworkflowYaml\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\x12(\n" +
	"\x10matrix_cell_json\x18\x05 \x01(\tR\x0ematrixCellJson\x12\x1d\n" +
	"\n" +
	"event_name\x18\x06 \x01(\tR\teventName\x12\x1d\n" +
	"\n" +
	"event_json\x18\a \x01(\tR\teventJson\x12\x19\n" +
	"\brepo_url\x18\b \x01(\tR\arepoUrl\x12\x10\n" +
	"\x03ref\x18\t \x01(\tR\x03ref\x12\x10\n" +
	"\x03sha\x18\n" +
	" \x01(\tR\x03sha\x12\x14\n" +
	"\x05actor\x18\v \x01(\tR\x05actor\x120\n" +
	"\x03env\x18\f \x03(\v2\x1e.dispatch.v1.JobLease.EnvEntryR\x03env\x123\n" +
	"\x04vars\x18\r \x03(\v2\x1f.dispatch.v1.JobLease.VarsEntryR\x04vars\x12<\n" +
	"\asecrets\x18\x0e \x03(\v2\".dispatch.v1.JobLease.SecretsEntryR\asecrets\x12L\n" +
	"\rneeds_outputs\x18\x0f \x03(\v2'.dispatch.v1.JobLease.NeedsOutputsEntryR\fneedsOutputs\x12.\n" +
	"\x13lease_deadline_unix\x18\x10 \x01(\x03R\x11leaseDeadlineUnix\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aY\n" +
	"\x11NeedsOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.dispatch.v1.NeedOutputsR\x05value:\x028\x01\"V\n" +
	"\rHeartbeatPing\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12(\n" +
	"\x10active_lease_ids\x18\x02 \x03(\tR\x0eactiveLeaseIds\"l\n" +
	"\fHeartbeatAck\x122\n" +
	"\x15next_interval_seconds\x18\x01 \x01(\x05R\x13nextIntervalSeconds\x12(\n" +
	"\x10cancel_lease_ids\x18\x02 \x03(\tR\x0ecancelLeaseIds\"\xc1\x01\n" +
	"\fStatusUpdate\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x1d\n" +
	"\n" +
	"step_index\x18\x03 \x01(\x05R\tstepIndex\x12\x1b\n" +
	"\tstep_name\x18\x04 \x01(\tR\bstepName\x12(\n" +
	"\x05phase\x18\x05 \x01(\x0e2\x12.dispatch.v1.PhaseR\x05phase\x12\x17\n" +
	"\ats_unix\x18\x06 \x01(\x03R\x06tsUnix\"\v\n" +
	"\tStatusAck\"}\n" +
	"\bLogChunk\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x17\n" +
	"\ats_unix\x18\x04 \x01(\x03R\x06tsUnix\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"\b\n" +
	"\x06LogAck\"\x84\x02\n" +
	"\x12CompleteJobRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12*\n" +
	"\x06result\x18\x02 \x01(\x0e2\x12.dispatch.v1.PhaseR\x06result\x12F\n" +
	"\aoutputs\x18\x03 \x03(\v2,.dispatch.v1.CompleteJobRequest.OutputsEntryR\aoutputs\x12#\n" +
	"\rerror_summary\x18\x04 \x01(\tR\ferrorSummary\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x15\n" +
	"\x13CompleteJobResponse*l\n" +
	"\n" +
	"RunnerMode\x12\x1b\n" +
	"\x17RUNNER_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10RUNNER_MODE_HOST\x10\x01\x12\x16\n" +
	"\x12RUNNER_MODE_DOCKER\x10\x02\x12\x13\n" +
	"\x0fRUNNER_MODE_K8S\x10\x03*\x92\x01\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPHASE_PENDING\x10\x01\x12\x11\n" +
	"\rPHASE_RUNNING\x10\x02\x12\x11\n" +
	"\rPHASE_SUCCESS\x10\x03\x12\x11\n" +
	"\rPHASE_FAILURE\x10\x04\x12\x11\n" +
	"\rPHASE_SKIPPED\x10\x05\x12\x13\n" +
	"\x0fPHASE_CANCELLED\x10\x062\xc5\x03\n" +
	"\bDispatch\x12Y\n" +
	"\x0eRegisterRunner\x12\".dispatch.v1.RegisterRunnerRequest\x1a#.dispatch.v1.RegisterRunnerResponse\x12E\n" +
	"\n" +
	"AcquireJob\x12\x1e.dispatch.v1.AcquireJobRequest\x1a\x15.dispatch.v1.JobLease0\x01\x12F\n" +
	"\tHeartbeat\x12\x1a.dispatch.v1.HeartbeatPing\x1a\x19.dispatch.v1.HeartbeatAck(\x010\x01\x12A\n" +
	"\fReportStatus\x12\x19.dispatch.v1.StatusUpdate\x1a\x16.dispatch.v1.StatusAck\x12:\n" +
	"\n" +
	"StreamLogs\x12\x15.dispatch.v1.LogChunk\x1a\x13.dispatch.v1.LogAck(\x01\x12P\n" +
	"\vCompleteJob\x12\x1f.dispatch.v1.CompleteJobRequest\x1a .dispatch.v1.CompleteJobResponseB\xad\x01\n" +
	"\x0fcom.dispatch.v1B\rDispatchProtoP\x01Z>github.com/chuan99nd/drassi-platform/pkg/dispatchpb;dispatchpb\xa2\x02\x03DXX\xaa\x02\vDispatch.V1\xca\x02\vDispatch\\V1\xe2\x02\x17Dispatch\\V1\\GPBMetadata\xea\x02\fDispatch::V1b\x06proto3"

var (
	file_dispatch_v1_dispatch_proto_rawDescOnce sync.Once
	file_dispatch_v1_dispatch_proto_rawDescData []byte
)

func file_dispatch_v1_dispatch_proto_rawDescGZIP() []byte {
	file_dispatch_v1_dispatch_proto_rawDescOnce.Do(func() {
		file_dispatch_v1_dispatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dispatch_v1_dispatch_proto_rawDesc), len(file_dispatch_v1_dispatch_proto_rawDesc)))
	})
	return file_dispatch_v1_dispatch_proto_rawDescData
}

var file_dispatch_v1_dispatch_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dispatch_v1_dispatch_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_dispatch_v1_dispatch_proto_goTypes = []any{
	(RunnerMode)(0),                // 0: dispatch.v1.RunnerMode
	(Phase)(0),                     // 1: dispatch.v1.Phase
	(*RegisterRunnerRequest)(nil),  // 2: dispatch.v1.RegisterRunnerRequest
	(*RegisterRunnerResponse)(nil), // 3: dispatch.v1.RegisterRunnerResponse
	(*AcquireJobRequest)(nil),      // 4: dispatch.v1.AcquireJobRequest
	(*NeedOutputs)(nil),            // 5: dispatch.v1.NeedOutputs
	(*JobLease)(nil),               // 6: dispatch.v1.JobLease
	(*HeartbeatPing)(nil),          // 7: dispatch.v1.HeartbeatPing
	(*HeartbeatAck)(nil),           // 8: dispatch.v1.HeartbeatAck
	(*StatusUpdate)(nil),           // 9: dispatch.v1.StatusUpdate
	(*StatusAck)(nil),              // 10: dispatch.v1.StatusAck
	(*LogChunk)(nil),               // 11: dispatch.v1.LogChunk
	(*LogAck)(nil),                 // 12: dispatch.v1.LogAck
	(*CompleteJobRequest)(nil),     // 13: dispatch.v1.CompleteJobRequest
	(*CompleteJobResponse)(nil),    // 14: dispatch.v1.CompleteJobResponse
	nil,                            // 15: dispatch.v1.NeedOutputs.OutputsEntry
	nil,                            // 16: dispatch.v1.JobLease.EnvEntry
	nil,                            // 17: dispatch.v1.JobLease.VarsEntry
	nil,                            // 18: dispatch.v1.JobLease.SecretsEntry
	nil,                            // 19: dispatch.v1.JobLease.NeedsOutputsEntry
	nil,                            // 20: dispatch.v1.CompleteJobRequest.OutputsEntry
}
var file_dispatch_v1_dispatch_proto_depIdxs = []int32{
	0,  // 0: dispatch.v1.RegisterRunnerRequest.mode:type_name -> dispatch.v1.RunnerMode
	15, // 1: dispatch.v1.NeedOutputs.outputs:type_name -> dispatch.v1.NeedOutputs.OutputsEntry
	16, // 2: dispatch.v1.JobLease.env:type_name -> dispatch.v1.JobLease.EnvEntry
	17, // 3: dispatch.v1.JobLease.vars:type_name -> dispatch.v1.JobLease.VarsEntry
	18, // 4: dispatch.v1.JobLease.secrets:type_name -> dispatch.v1.JobLease.SecretsEntry
	19, // 5: dispatch.v1.JobLease.needs_outputs:type_name -> dispatch.v1.JobLease.NeedsOutputsEntry
	1,  // 6: dispatch.v1.StatusUpdate.phase:type_name -> dispatch.v1.Phase
	1,  // 7: dispatch.v1.CompleteJobRequest.result:type_name -> dispatch.v1.Phase
	20, // 8: dispatch.v1.CompleteJobRequest.outputs:type_name -> dispatch.v1.CompleteJobRequest.OutputsEntry
	5,  // 9: dispatch.v1.JobLease.NeedsOutputsEntry.value:type_name -> dispatch.v1.NeedOutputs
	2,  // 10: dispatch.v1.Dispatch.RegisterRunner:input_type -> dispatch.v1.RegisterRunnerRequest
	4,  // 11: dispatch.v1.Dispatch.AcquireJob:input_type -> dispatch.v1.AcquireJobRequest
	7,  // 12: dispatch.v1.Dispatch.Heartbeat:input_type -> dispatch.v1.HeartbeatPing
	9,  // 13: dispatch.v1.Dispatch.ReportStatus:input_type -> dispatch.v1.StatusUpdate
	11, // 14: dispatch.v1.Dispatch.StreamLogs:input_type -> dispatch.v1.LogChunk
	13, // 15: dispatch.v1.Dispatch.CompleteJob:input_type -> dispatch.v1.CompleteJobRequest
	3,  // 16: dispatch.v1.Dispatch.RegisterRunner:output_type -> dispatch.v1.RegisterRunnerResponse
	6,  // 17: dispatch.v1.Dispatch.AcquireJob:output_type -> dispatch.v1.JobLease
	8,  // 18: dispatch.v1.Dispatch.Heartbeat:output_type -> dispatch.v1.HeartbeatAck
	10, // 19: dispatch.v1.Dispatch.ReportStatus:output_type -> dispatch.v1.StatusAck
	12, // 20: dispatch.v1.Dispatch.StreamLogs:output_type -> dispatch.v1.LogAck
	14, // 21: dispatch.v1.Dispatch.CompleteJob:output_type -> dispatch.v1.CompleteJobResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_dispatch_v1_dispatch_proto_init() }
func file_dispatch_v1_dispatch_proto_init() {
	if File_dispatch_v1_dispatch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dispatch_v1_dispatch_proto_rawDesc), len(file_dispatch_v1_dispatch_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dispatch_v1_dispatch_proto_goTypes,
		DependencyIndexes: file_dispatch_v1_dispatch_proto_depIdxs,
		EnumInfos:         file_dispatch_v1_dispatch_proto_enumTypes,
		MessageInfos:      file_dispatch_v1_dispatch_proto_msgTypes,
	}.Build()
	File_dispatch_v1_dispatch_proto = out.File
	file_dispatch_v1_dispatch_proto_goTypes = nil
	file_dispatch_v1_dispatch_proto_depIdxs = nil
}
