// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: dispatch/v1/dispatch.proto

package dispatchpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dispatch_RegisterRunner_FullMethodName = "/dispatch.v1.Dispatch/RegisterRunner"
	Dispatch_AcquireJob_FullMethodName     = "/dispatch.v1.Dispatch/AcquireJob"
	Dispatch_Heartbeat_FullMethodName      = "/dispatch.v1.Dispatch/Heartbeat"
	Dispatch_ReportStatus_FullMethodName   = "/dispatch.v1.Dispatch/ReportStatus"
	Dispatch_StreamLogs_FullMethodName     = "/dispatch.v1.Dispatch/StreamLogs"
	Dispatch_CompleteJob_FullMethodName    = "/dispatch.v1.Dispatch/CompleteJob"
)

// DispatchClient is the client API for Dispatch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dispatch is the runner-facing control plane. Every RPC is dialed OUT by the
// runner, so runners need no inbound ports (pull-based model). Secure the
// channel with mTLS in production; the runner also presents the auth_token it
// received at registration.
type DispatchClient interface {
	// RegisterRunner announces a runner and returns its identity + auth token.
	RegisterRunner(ctx context.Context, in *RegisterRunnerRequest, opts ...grpc.CallOption) (*RegisterRunnerResponse, error)
	// AcquireJob is a server-stream: the orchestrator pushes one JobLease per
	// free slot as jobs become runnable. The runner keeps this open.
	AcquireJob(ctx context.Context, in *AcquireJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobLease], error)
	// Heartbeat is bidirectional: pings renew leases + report liveness; acks may
	// carry control signals (e.g. cancel a lease).
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatPing, HeartbeatAck], error)
	// ReportStatus records a per-step (or job) state transition.
	ReportStatus(ctx context.Context, in *StatusUpdate, opts ...grpc.CallOption) (*StatusAck, error)
	// StreamLogs is a client-stream of ordered log chunks for one lease.
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogChunk, LogAck], error)
	// CompleteJob finalizes a lease with its result and outputs.
	CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error)
}

type dispatchClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchClient(cc grpc.ClientConnInterface) DispatchClient {
	return &dispatchClient{cc}
}

func (c *dispatchClient) RegisterRunner(ctx context.Context, in *RegisterRunnerRequest, opts ...grpc.CallOption) (*RegisterRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterRunnerResponse)
	err := c.cc.Invoke(ctx, Dispatch_RegisterRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchClient) AcquireJob(ctx context.Context, in *AcquireJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobLease], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Dispatch_ServiceDesc.Streams[0], Dispatch_AcquireJob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AcquireJobRequest, JobLease]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_AcquireJobClient = grpc.ServerStreamingClient[JobLease]

func (c *dispatchClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatPing, HeartbeatAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Dispatch_ServiceDesc.Streams[1], Dispatch_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatPing, HeartbeatAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatPing, HeartbeatAck]

func (c *dispatchClient) ReportStatus(ctx context.Context, in *StatusUpdate, opts ...grpc.CallOption) (*StatusAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusAck)
	err := c.cc.Invoke(ctx, Dispatch_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogChunk, LogAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Dispatch_ServiceDesc.Streams[2], Dispatch_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogChunk, LogAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_StreamLogsClient = grpc.ClientStreamingClient[LogChunk, LogAck]

func (c *dispatchClient) CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteJobResponse)
	err := c.cc.Invoke(ctx, Dispatch_CompleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatchServer is the server API for Dispatch service.
// All implementations must embed UnimplementedDispatchServer
// for forward compatibility.
//
// Dispatch is the runner-facing control plane. Every RPC is dialed OUT by the
// runner, so runners need no inbound ports (pull-based model). Secure the
// channel with mTLS in production; the runner also presents the auth_token it
// received at registration.
type DispatchServer interface {
	// RegisterRunner announces a runner and returns its identity + auth token.
	RegisterRunner(context.Context, *RegisterRunnerRequest) (*RegisterRunnerResponse, error)
	// AcquireJob is a server-stream: the orchestrator pushes one JobLease per
	// free slot as jobs become runnable. The runner keeps this open.
	AcquireJob(*AcquireJobRequest, grpc.ServerStreamingServer[JobLease]) error
	// Heartbeat is bidirectional: pings renew leases + report liveness; acks may
	// carry control signals (e.g. cancel a lease).
	Heartbeat(grpc.BidiStreamingServer[HeartbeatPing, HeartbeatAck]) error
	// ReportStatus records a per-step (or job) state transition.
	ReportStatus(context.Context, *StatusUpdate) (*StatusAck, error)
	// StreamLogs is a client-stream of ordered log chunks for one lease.
	StreamLogs(grpc.ClientStreamingServer[LogChunk, LogAck]) error
	// CompleteJob finalizes a lease with its result and outputs.
	CompleteJob(context.Context, *CompleteJobRequest) (*CompleteJobResponse, error)
	mustEmbedUnimplementedDispatchServer()
}

// UnimplementedDispatchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDispatchServer struct{}

func (UnimplementedDispatchServer) RegisterRunner(context.Context, *RegisterRunnerRequest) (*RegisterRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterRunner not implemented")
}
func (UnimplementedDispatchServer) AcquireJob(*AcquireJobRequest, grpc.ServerStreamingServer[JobLease]) error {
	return status.Error(codes.Unimplemented, "method AcquireJob not implemented")
}
func (UnimplementedDispatchServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatPing, HeartbeatAck]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedDispatchServer) ReportStatus(context.Context, *StatusUpdate) (*StatusAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedDispatchServer) StreamLogs(grpc.ClientStreamingServer[LogChunk, LogAck]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedDispatchServer) CompleteJob(context.Context, *CompleteJobRequest) (*CompleteJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteJob not implemented")
}
func (UnimplementedDispatchServer) mustEmbedUnimplementedDispatchServer() {}
func (UnimplementedDispatchServer) testEmbeddedByValue()                  {}

// UnsafeDispatchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatchServer will
// result in compilation errors.
type UnsafeDispatchServer interface {
	mustEmbedUnimplementedDispatchServer()
}

func RegisterDispatchServer(s grpc.ServiceRegistrar, srv DispatchServer) {
	// If the following call panics, it indicates UnimplementedDispatchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dispatch_ServiceDesc, srv)
}

func _Dispatch_RegisterRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).RegisterRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_RegisterRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).RegisterRunner(ctx, req.(*RegisterRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatch_AcquireJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AcquireJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DispatchServer).AcquireJob(m, &grpc.GenericServerStream[AcquireJobRequest, JobLease]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_AcquireJobServer = grpc.ServerStreamingServer[JobLease]

func _Dispatch_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DispatchServer).Heartbeat(&grpc.GenericServerStream[HeartbeatPing, HeartbeatAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatPing, HeartbeatAck]

func _Dispatch_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).ReportStatus(ctx, req.(*StatusUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatch_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DispatchServer).StreamLogs(&grpc.GenericServerStream[LogChunk, LogAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_StreamLogsServer = grpc.ClientStreamingServer[LogChunk, LogAck]

func _Dispatch_CompleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).CompleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_CompleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).CompleteJob(ctx, req.(*CompleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dispatch_ServiceDesc is the grpc.ServiceDesc for Dispatch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dispatch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dispatch.v1.Dispatch",
	HandlerType: (*DispatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRunner",
			Handler:    _Dispatch_RegisterRunner_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _Dispatch_ReportStatus_Handler,
		},
		{
			MethodName: "CompleteJob",
			Handler:    _Dispatch_CompleteJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AcquireJob",
			Handler:       _Dispatch_AcquireJob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Heartbeat",
			Handler:       _Dispatch_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _Dispatch_StreamLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "dispatch/v1/dispatch.proto",
}
